name: GBS Tizen build for x64 from Ubuntu

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v1
    - name: prepare deb sources for GBS
      run: echo "deb [trusted=yes] http://download.tizen.org/tools/latest-release/Ubuntu_20.04/ /" | sudo tee /etc/apt/sources.list.d/tizen.list
    - name: install GBS
      run: sudo apt-get update && sudo apt-get install -y gbs
    - name: configure GBS
      run: cp .github/workflows/tizen.gbs.conf ~/.gbs.conf
    - name: Make cache key
      id: make-key
      run: echo "cache_key=$(date +'%Y-%m-%d')-Tizen-Unified-reference" >> $GITHUB_OUTPUT
      shell: bash
    - name: Caching GBS-ROOT
      id: cache-gbs-root
      uses: actions/cache@v3
      with:
        path: ~/GBS-ROOT/local/cache
        key: ${{ steps.make-key.outputs.cache_key }}
    - name: cache miss
      if: steps.cache-gbs-root.outputs.cache-hit != 'true'
      run: |
        echo "cache miss"
    - name: cache hit
      if: steps.cache-gbs-root.outputs.cache-hit == 'true'
      run: |
        echo "cache hit"
        echo "$(ls -al ~/GBS-ROOT/local/cache)"
    - name: run GBS
      run: gbs build
